### PR TITLE
Add toolbar with 'stop' button to visualizer

### PR DESCRIPTION
**Pull request by tkoolen**
Stop button sends an LCM message that is received on the Julia side, and used to call `terminate!` on the integrator in a DiffEq `solve` callback. Also reorganized things a bit.

### CODE REVIEW

**Comment by tkoolen** [comment]
Requires https://github.com/rdeits/DrakeVisualizer.jl/pull/62, https://github.com/rdeits/LCMCore.jl/pull/15.

**Comment by tkoolen** [comment]
Thanks for the `yield` tip @rdeits, that worked.

**Comment by rdeits** [comment]
Excellent!

**Comment by tkoolen** [comment]
Probably shouldn't `yield` every integrator time step though:
```julia
julia> @benchmark yield()
BenchmarkTools.Trial: 
  memory estimate:  16 bytes
  allocs estimate:  1
  --------------
  minimum time:     1.018 μs (0.00% GC)
  median time:      1.046 μs (0.00% GC)
  mean time:        1.063 μs (0.00% GC)
  maximum time:     3.082 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     11
```
(I hope using `@benchmark` for this actually makes sense)

**Pull request merged**
